### ISSUE TITLE
Login/Logout stuff

### ISSUE THREAD

**Issue by huonglarne** [dinhanhx/flickr#4]
1. Need to create a UI for login/logout @DDHLong 
2. Connect it to the Flickr API @dinhanhx

**Comment by huonglarne** [comment]
Only the UI has been created. Now,
1. Need to write some view pager or something for the landing site
2. Need to connect it to Flickr API to access user info and database stuff

**Comment by DDHLong** [comment]
I totally don't get what you mean and please divide it into smaller issues
